# Use root/example as user/password credentials
version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - db-perso:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user1234
      MONGO_INITDB_ROOT_PASSWORD: user1234

volumes:
  db-perso: